apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: oci-pv-claim-1
spec:
  storageClassName: "oci"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: oci-pv-claim-2
spec:
  storageClassName: "oci"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: oci-pv-claim-3
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: oci-pv-claim-4
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
