apiVersion: apps/v1
kind: Deployment
metadata:
  name: db
  namespace: vote
  labels:
    app: db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "true"
      labels:
        app: db
    spec:
      containers:
        # - image: postgres:9.4
        # - image: registry.access.redhat.com/rhscl/postgresql-94-rhel7
        - image: rhscl/postgresql-10-rhel7
        # - image: centos/postgresql-94-centos7
          # name: db
          name: postgres
          env:
            - name: POSTGRES_USER
              value: user2
            - name: POSTGRES_PASSWORD
              value: postgres
            - name: POSTGRESQL_USER
              value: user1
            - name: POSTGRESQL_DATABASE
              value: db1
            - name: POSTGRESQL_PASSWORD
              value: postgres
            - name: POSTGRESQL_ADMIN_PASSWORD
              value: postgres
            - name: POSTGRES_HOST_AUTH_METHOD
              value: trust
          volumeMounts:
            # - mountPath: /var/lib/postgresql/data:Z
            - mountPath: /var/lib/postgresql/data
              name: db-data
      volumes:
        - name: db-data
          emptyDir: {}
