apiVersion: apps/v1
kind: Deployment
metadata:
  name: result
  # namespace: result
  namespace: vote
spec:
  replicas: 1
  selector:
    matchLabels:
      app: result
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "true"
      labels:
        app: result
    spec:
      containers:
        # - image: dyangcht/examplevotingapp_result:before
        - image: dyangcht/examplevotingapp_result:v1
          name: result
