apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
  namespace: vote
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "true"
      labels:
        app: worker
    spec:
      containers:
        # - image: dockersamples/examplevotingapp_worker
        - image: dyangcht/worker:v1.3
          name: worker
