apiVersion: v1
kind: Service
metadata:
  name: vote
  namespace: app1
spec:
  # type: NodePort
  ports:
    - name: "http-vote-service"
      port: 8081
      targetPort: 8081
      # nodePort: 31000
  selector:
    app: vote
