apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: db
  name: db
  namespace: vote
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
      - image: registry.redhat.io/rhel8/postgresql-96
        name: postgres
        env:
        - name: POSTGRESQL_USER
          value: user1
        - name: POSTGRESQL_PASSWORD
          value: postgres
        - name: POSTGRESQL_DATABASE
          value: vote
        ports:
        - containerPort: 5432
          name: postgres
        volumeMounts:
        - mountPath: /var/lib/pgsql/data
          name: db-data
      volumes:
      - name: db-data
        # emptyDir: {}
        persistentVolumeClaim:
          claimName: postgres-pv-claim
