apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: worker
  namespace: vote
spec:
  replicas: 1
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "true"
      labels:
        app: worker
    spec:
      containers:
        - image: dockersamples/examplevotingapp_worker
          name: worker
